#Install Pandas

In [ ]:
#There are several ways to install a python package
#one way is using pip (pip install packages)
#pip can be executed in linux terminal to intsall packages in local machine
#In Google Colab, use ! to run a linux command

!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

#Import pandas in your program
Everytime after your runtime is disconnected you have to import the module

In [ ]:
#import all the entire pandas module into pd (a name of your choice)
import pandas as pd
import numpy as np
type(pd)

module

#Dataframe and Series: Pandas fundamental datastructure

In [ ]:
#Create a dictionry
data = {
    'id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Cindy', 'David', 'Elizabeth']
}
type(data)

dict

In [ ]:
#Read the dictionary into pandas
df = pd.DataFrame(data) #Read the entire dictionary with two columns (id and name) as a Dataframe
df
srs = pd.Series(data['id'])
print(type(srs))
srs
#print(type(df['id'])) #Each column of a dataframe is also a series

<class 'pandas.core.series.Series'>

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#Convert a numpy array to Pandas and viceversa

import numpy as np
my_array = np.array([[11,22,33],
                     [44,55,66]])#Creating a numpy array

df = pd.DataFrame(my_array, columns = ['Column_A','Column_B','Column_C']) #convert from numpy to Pandas

print(df)
print(type(df))

narray = df.to_numpy() #convert from  Pandas to numpy
print(narray)
print(type(narray))

   Column_A  Column_B  Column_C
0        11        22        33
1        44        55        66
<class 'pandas.core.frame.DataFrame'>
[[11 22 33]
 [44 55 66]]
<class 'numpy.ndarray'>

#Read a csv file into pandas dataframe
Everyrime your runtime is disconnected you have to create the datframe again

In [ ]:
#Read a file available over internet
#(I made this file available publicly. We will use it for today's workshop.)
file_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQL0mu4CnfA3o4cE_aXdkVIgb3x28aV1ayVohgpBw4EKYV0DmUFr5mcuXRyYvoUUjXXJnc6e9Mabp3f/pub?output=csv'
df_cancer = pd.read_csv(file_url)
type(df_cancer)
#df_cancer

pandas.core.frame.DataFrame

**Follwing blocks of codes are showing other scenarios to read a file**

You should change the file_path, file_id, file_url, etc. to make it working properly.

In [ ]:
#Read a file in your local machine
file_path = '/path/to/your/data_file.csv'
pd.read_csv(file_path)

In [ ]:
#Read a csv file stored in your google drive
file_id = '1u15c4jRiiCBfzuvxDld65h_in88oFjny' #Replace it with your file_id: 
                                              #right click on the file >> get url >> change permission from 'Restricted' to 'Anyone with this link' >> Copy the id 
file_url = 'https://drive.google.com/uc?id=' + file_id #First part is how Google publish a file (same for any file)

df_cancer = pd.read_csv(file_url)
df_cancer

In [ ]:
#Read a google spreadsheet
#First publish it on the web as csv: File >> Share >> Publish on the web >> Select Entire document (left dropdown) 
                                     #>> Select Comma Separated Value (right drop down) >> Publish >> Copy the url 
file_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSxuqWA__mPgb5p0abdX5MsV64mijIs_wblVo6j-H3vuSLgG8c_RirNMc1zHX_FCXdWgBgbv0VtCNgq/pub?output=csv'
df_cancer = pd.read_csv(file_url)
df_cancer

#Explore the data

In [ ]:
#Read a file available over internet (Copy-paste the previous block so that I don't need to scroll too much)
#In this section, I will make some changes in my file and you should be able to see those changes in your program)
file_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQL0mu4CnfA3o4cE_aXdkVIgb3x28aV1ayVohgpBw4EKYV0DmUFr5mcuXRyYvoUUjXXJnc6e9Mabp3f/pub?output=csv'
df_cancer = pd.read_csv(file_url)
#type(df_cancer)
df_cancer

,%id,diagnosis (M=malignant; B=benign),radius (nucA),texture (nucA),perimeter (nucA),area (nucA),smoothness (nucA),compactness (nucA),concavity (nucA),concave points (nucA),...,radius (nucC),texture (nucC),perimeter (nucC),area (nucC),smoothness (nucC),compactness (nucC),concavity (nucC),concave points (nucC),symmetry (nucC),fractal dimension (nucC)
0,842302,NaN,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
#Get some information of the data
#df_cancer.info() #Get the info of a dataframe

#df_cancer.columns
for col in df_cancer.columns:
 print(df_cancer[col].describe()) #Get info of a series (a particular column of a dataframe)

#print(df_cancer.describe)

count    5.690000e+02
mean     3.037183e+07
std      1.250206e+08
min      8.670000e+03
25%      8.692180e+05
50%      9.060240e+05
75%      8.813129e+06
max      9.113205e+08
Name: %id, dtype: float64
count     568
unique      2
top         B
freq      357
Name: diagnosis (M=malignant; B=benign), dtype: object
count    569.000000
mean      14.127292
std        3.524049
min        6.981000
25%       11.700000
50%       13.370000
75%       15.780000
max       28.110000
Name: radius (nucA), dtype: float64
count    569.000000
mean      19.289649
std        4.301036
min        9.710000
25%       16.170000
50%       18.840000
75%       21.800000
max       39.280000
Name: texture (nucA), dtype: float64
count    569.000000
mean      91.969033
std       24.298981
min       43.790000
25%       75.170000
50%       86.240000
75%      104.100000
max      188.500000
Name: perimeter (nucA), dtype: float64
count     569.000000
mean      654.889104
std       351.914129
min       143.500000
25%       420.300000
50%       551.100000
75%       782.700000
max      2501.000000
Name: area (nucA), dtype: float64
count    569.000000
mean       0.096360
std        0.014064
min        0.052630
25%        0.086370
50%        0.095870
75%        0.105300
max        0.163400
Name: smoothness (nucA), dtype: float64
count    569.000000
mean       0.104341
std        0.052813
min        0.019380
25%        0.064920
50%        0.092630
75%        0.130400
max        0.345400
Name: compactness (nucA), dtype: float64
count    569.000000
mean       0.088799
std        0.079720
min        0.000000
25%        0.029560
50%        0.061540
75%        0.130700
max        0.426800
Name: concavity (nucA), dtype: float64
count    569.000000
mean       0.048919
std        0.038803
min        0.000000
25%        0.020310
50%        0.033500
75%        0.074000
max        0.201200
Name: concave points (nucA), dtype: float64
count    569.000000
mean       0.181162
std        0.027414
min        0.106000
25%        0.161900
50%        0.179200
75%        0.195700
max        0.304000
Name: symmetry (nucA), dtype: float64
count    569.000000
mean       0.062798
std        0.007060
min        0.049960
25%        0.057700
50%        0.061540
75%        0.066120
max        0.097440
Name: fractal dimension (nucA), dtype: float64
count    569.000000
mean       0.405172
std        0.277313
min        0.111500
25%        0.232400
50%        0.324200
75%        0.478900
max        2.873000
Name: radius (nucB), dtype: float64
count    569.000000
mean       1.216853
std        0.551648
min        0.360200
25%        0.833900
50%        1.108000
75%        1.474000
max        4.885000
Name: texture (nucB), dtype: float64
count    569.000000
mean       2.866059
std        2.021855
min        0.757000
25%        1.606000
50%        2.287000
75%        3.357000
max       21.980000
Name: perimeter (nucB), dtype: float64
count    569.000000
mean      40.337079
std       45.491006
min        6.802000
25%       17.850000
50%       24.530000
75%       45.190000
max      542.200000
Name: area (nucB), dtype: float64
count    569.000000
mean       0.007041
std        0.003003
min        0.001713
25%        0.005169
50%        0.006380
75%        0.008146
max        0.031130
Name: smoothness (nucB), dtype: float64
count    569.000000
mean       0.025478
std        0.017908
min        0.002252
25%        0.013080
50%        0.020450
75%        0.032450
max        0.135400
Name: compactness (nucB), dtype: float64
count    569.000000
mean       0.031894
std        0.030186
min        0.000000
25%        0.015090
50%        0.025890
75%        0.042050
max        0.396000
Name: concavity (nucB), dtype: float64
count    569.000000
mean       0.011796
std        0.006170
min        0.000000
25%        0.007638
50%        0.010930
75%        0.014710
max        0.052790
Name: concave points (nucB), dtype: float64
count    569.000000
mean       0.020542
std        0.008266
min        0.007882
25%        0.015160
50%        0.018730
75%        0.023480
max        0.078950
Name: symmetry (nucB), dtype: float64
count    569.000000
mean       0.003795
std        0.002646
min        0.000895
25%        0.002248
50%        0.003187
75%        0.004558
max        0.029840
Name: fractal dimension (nucB), dtype: float64
count    569.000000
mean      16.269190
std        4.833242
min        7.930000
25%       13.010000
50%       14.970000
75%       18.790000
max       36.040000
Name: radius (nucC), dtype: float64
count    569.000000
mean      25.677223
std        6.146258
min       12.020000
25%       21.080000
50%       25.410000
75%       29.720000
max       49.540000
Name: texture (nucC), dtype: float64
count    569.000000
mean     107.261213
std       33.602542
min       50.410000
25%       84.110000
50%       97.660000
75%      125.400000
max      251.200000
Name: perimeter (nucC), dtype: float64
count     569.000000
mean      880.583128
std       569.356993
min       185.200000
25%       515.300000
50%       686.500000
75%      1084.000000
max      4254.000000
Name: area (nucC), dtype: float64
count    569.000000
mean       0.132369
std        0.022832
min        0.071170
25%        0.116600
50%        0.131300
75%        0.146000
max        0.222600
Name: smoothness (nucC), dtype: float64
count    569.000000
mean       0.254265
std        0.157336
min        0.027290
25%        0.147200
50%        0.211900
75%        0.339100
max        1.058000
Name: compactness (nucC), dtype: float64
count    569.000000
mean       0.272188
std        0.208624
min        0.000000
25%        0.114500
50%        0.226700
75%        0.382900
max        1.252000
Name: concavity (nucC), dtype: float64
count    569.000000
mean       0.114606
std        0.065732
min        0.000000
25%        0.064930
50%        0.099930
75%        0.161400
max        0.291000
Name: concave points (nucC), dtype: float64
count    569.000000
mean       0.290076
std        0.061867
min        0.156500
25%        0.250400
50%        0.282200
75%        0.317900
max        0.663800
Name: symmetry (nucC), dtype: float64
count    569.000000
mean       0.083946
std        0.018061
min        0.055040
25%        0.071460
50%        0.080040
75%        0.092080
max        0.207500
Name: fractal dimension (nucC), dtype: float64

In [ ]:
#Change a column to a particular type to make it memory efficient
df_cancer['%id'] = df_cancer['%id'].astype(np.int32)
df_cancer['%id'].dtype

dtype('int32')

In [ ]:
#Name of all the columns
df_cancer.columns

Index(['%id', 'diagnosis (M=malignant; B=benign)', 'radius (nucA)',
       'texture (nucA)', 'perimeter (nucA)', 'area (nucA)',
       'smoothness (nucA)', 'compactness (nucA)', 'concavity (nucA)',
       'concave points (nucA)', 'symmetry (nucA)', 'fractal dimension (nucA)',
       'radius (nucB)', 'texture (nucB)', 'perimeter (nucB)', 'area (nucB)',
       'smoothness (nucB)', 'compactness (nucB)', 'concavity (nucB)',
       'concave points (nucB)', 'symmetry (nucB)', 'fractal dimension (nucB)',
       'radius (nucC)', 'texture (nucC)', 'perimeter (nucC)', 'area (nucC)',
       'smoothness (nucC)', 'compactness (nucC)', 'concavity (nucC)',
       'concave points (nucC)', 'symmetry (nucC)', 'fractal dimension (nucC)'],
      dtype='object')

In [ ]:
#Number of columns are in the data frame
len(df_cancer.columns)

32

In [ ]:
#Number of rows and columns
df_cancer.shape

(569, 32)

In [ ]:
n = 2
#read first n rows in a dataframe
df_cancer.head(n)

,%id,diagnosis (M=malignant; B=benign),radius (nucA),texture (nucA),perimeter (nucA),area (nucA),smoothness (nucA),compactness (nucA),concavity (nucA),concave points (nucA),...,radius (nucC),texture (nucC),perimeter (nucC),area (nucC),smoothness (nucC),compactness (nucC),concavity (nucC),concave points (nucC),symmetry (nucC),fractal dimension (nucC)
0,842302,NaN,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902

In [ ]:
n = 2
#read last n rows in a dataframe
df_cancer.tail(n)

,%id,diagnosis (M=malignant; B=benign),radius (nucA),texture (nucA),perimeter (nucA),area (nucA),smoothness (nucA),compactness (nucA),concavity (nucA),concave points (nucA),...,radius (nucC),texture (nucC),perimeter (nucC),area (nucC),smoothness (nucC),compactness (nucC),concavity (nucC),concave points (nucC),symmetry (nucC),fractal dimension (nucC)
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.3514,0.152,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.265,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.0000,0.000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.000,0.2871,0.07039

In [ ]:
#Check if there is any null value in the dataframe
#df_cancer.isnull() #checks each CELL if there is a null
df_cancer.isnull().sum() #Total number of null cells

%id                                  0
diagnosis (M=malignant; B=benign)    1
radius (nucA)                        0
texture (nucA)                       0
perimeter (nucA)                     0
area (nucA)                          0
smoothness (nucA)                    0
compactness (nucA)                   0
concavity (nucA)                     0
concave points (nucA)                0
symmetry (nucA)                      0
fractal dimension (nucA)             0
radius (nucB)                        0
texture (nucB)                       0
perimeter (nucB)                     0
area (nucB)                          0
smoothness (nucB)                    0
compactness (nucB)                   0
concavity (nucB)                     0
concave points (nucB)                0
symmetry (nucB)                      0
fractal dimension (nucB)             0
radius (nucC)                        0
texture (nucC)                       0
perimeter (nucC)                     0
area (nucC)                          0
smoothness (nucC)                    0
compactness (nucC)                   0
concavity (nucC)                     0
concave points (nucC)                0
symmetry (nucC)                      0
fractal dimension (nucC)             0
dtype: int64

In [ ]:
#Check if there is any duplicate
df_cancer.duplicated() #Checks each ROW if it is duplicated
#df_cancer.duplicated().sum() #Total number of duplicated rows

0      False
1      False
2      False
3      False
4      False
       ...
564    False
565    False
566    False
567    False
568    False
Length: 569, dtype: bool

In [ ]:
#Get the duplicated rows
df_cancer[df_cancer.duplicated()] #it checks all the rows for duplicated values. Whenever it is a True, print it

Empty DataFrame
Columns: [%id, diagnosis (M=malignant; B=benign), radius (nucA), texture (nucA), perimeter (nucA), area (nucA), smoothness (nucA), compactness (nucA), concavity (nucA), concave points (nucA), symmetry (nucA), fractal dimension (nucA), radius (nucB), texture (nucB), perimeter (nucB), area (nucB), smoothness (nucB), compactness (nucB), concavity (nucB), concave points (nucB), symmetry (nucB), fractal dimension (nucB), radius (nucC), texture (nucC), perimeter (nucC), area (nucC), smoothness (nucC), compactness (nucC), concavity (nucC), concave points (nucC), symmetry (nucC), fractal dimension (nucC)]
Index: []

[0 rows x 32 columns]

#Preprocess the data

In [ ]:
#Read a file available over internet (Copy-paste the previous block so that I don't need to scroll too much)
#In this section, I will make some changes in my file and you should be able to see those changes in your program)
file_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQL0mu4CnfA3o4cE_aXdkVIgb3x28aV1ayVohgpBw4EKYV0DmUFr5mcuXRyYvoUUjXXJnc6e9Mabp3f/pub?output=csv'
df_cancer = pd.read_csv(file_url)
#type(df_cancer)
df_cancer

,%id,diagnosis (M=malignant; B=benign),radius (nucA),texture (nucA),perimeter (nucA),area (nucA),smoothness (nucA),compactness (nucA),concavity (nucA),concave points (nucA),...,radius (nucC),texture (nucC),perimeter (nucC),area (nucC),smoothness (nucC),compactness (nucC),concavity (nucC),concave points (nucC),symmetry (nucC),fractal dimension (nucC)
0,842302,NaN,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
#Remove duplicates
df_cancer.drop_duplicates(inplace=True) #If you do not use inplace=True it will create another copy of the dataframe with no duplicate rows
print(sum(df_cancer.duplicated()))

0

In [ ]:
#Remove null values
df_cancer.dropna(inplace=True, axis=0) #If you do not use inplace=True it will create another copy of the dataframe with no null values
df_cancer

,%id,diagnosis (M=malignant; B=benign),radius (nucA),texture (nucA),perimeter (nucA),area (nucA),smoothness (nucA),compactness (nucA),concavity (nucA),concave points (nucA),...,radius (nucC),texture (nucC),perimeter (nucC),area (nucC),smoothness (nucC),compactness (nucC),concavity (nucC),concave points (nucC),symmetry (nucC),fractal dimension (nucC)
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,15.470,23.75,103.40,741.6,0.17910,0.52490,0.5355,0.1741,0.3985,0.12440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
#Renaming columns (This may impact following blocks)
print(df_cancer.columns)
df_cancer.rename(columns={
    '%id': 'id',
    'diagnosis (M=malignant; B=benign)': 'diagnosis'
}, inplace=True)
print(df_cancer.columns)

Index(['%id', 'diagnosis (M=malignant; B=benign)', 'radius (nucA)',
       'texture (nucA)', 'perimeter (nucA)', 'area (nucA)',
       'smoothness (nucA)', 'compactness (nucA)', 'concavity (nucA)',
       'concave points (nucA)', 'symmetry (nucA)', 'fractal dimension (nucA)',
       'radius (nucB)', 'texture (nucB)', 'perimeter (nucB)', 'area (nucB)',
       'smoothness (nucB)', 'compactness (nucB)', 'concavity (nucB)',
       'concave points (nucB)', 'symmetry (nucB)', 'fractal dimension (nucB)',
       'radius (nucC)', 'texture (nucC)', 'perimeter (nucC)', 'area (nucC)',
       'smoothness (nucC)', 'compactness (nucC)', 'concavity (nucC)',
       'concave points (nucC)', 'symmetry (nucC)', 'fractal dimension (nucC)'],
      dtype='object')
Index(['id', 'diagnosis', 'radius (nucA)', 'texture (nucA)',
       'perimeter (nucA)', 'area (nucA)', 'smoothness (nucA)',
       'compactness (nucA)', 'concavity (nucA)', 'concave points (nucA)',
       'symmetry (nucA)', 'fractal dimension (nucA)', 'radius (nucB)',
       'texture (nucB)', 'perimeter (nucB)', 'area (nucB)',
       'smoothness (nucB)', 'compactness (nucB)', 'concavity (nucB)',
       'concave points (nucB)', 'symmetry (nucB)', 'fractal dimension (nucB)',
       'radius (nucC)', 'texture (nucC)', 'perimeter (nucC)', 'area (nucC)',
       'smoothness (nucC)', 'compactness (nucC)', 'concavity (nucC)',
       'concave points (nucC)', 'symmetry (nucC)', 'fractal dimension (nucC)'],
      dtype='object')

#Maths and stats on dataframe/series

In [ ]:
#Calculate average
#df_cancer.mean(numeric_only=True) #average of all numeric columns
df_cancer['radius (nucA)'].mean() #average of a particular column (or a series)

14.1204911971831

In [ ]:
#Calculate max
#df_cancer.max(numeric_only=True) #max of each numeric column
df_cancer['radius (nucA)'].max() #max of a particular column (or a series)

28.11

In [ ]:
#Calculate min
df_cancer.min(numeric_only=True) #min of each numeric column
#df_cancer['radius (nucA)'].min() #min of a particular column (or a series)

id                          8670.000000
radius (nucA)                  6.981000
texture (nucA)                 9.710000
perimeter (nucA)              43.790000
area (nucA)                  143.500000
smoothness (nucA)              0.052630
compactness (nucA)             0.019380
concavity (nucA)               0.000000
concave points (nucA)          0.000000
symmetry (nucA)                0.106000
fractal dimension (nucA)       0.049960
radius (nucB)                  0.111500
texture (nucB)                 0.360200
perimeter (nucB)               0.757000
area (nucB)                    6.802000
smoothness (nucB)              0.001713
compactness (nucB)             0.002252
concavity (nucB)               0.000000
concave points (nucB)          0.000000
symmetry (nucB)                0.007882
fractal dimension (nucB)       0.000895
radius (nucC)                  7.930000
texture (nucC)                12.020000
perimeter (nucC)              50.410000
area (nucC)                  185.200000
smoothness (nucC)              0.071170
compactness (nucC)             0.027290
concavity (nucC)               0.000000
concave points (nucC)          0.000000
symmetry (nucC)                0.156500
fractal dimension (nucC)       0.055040
dtype: float64

In [ ]:
#Calculate standard deviation
df_cancer.std(numeric_only=True) #standard deviation of each numeric column
#df_cancer['radius (nucA)'].std() #standard deviation of a particular column (or a series)

id                          1.251246e+08
radius (nucA)               3.523416e+00
texture (nucA)              4.288506e+00
perimeter (nucA)            2.428585e+01
area (nucA)                 3.519238e+02
smoothness (nucA)           1.404601e-02
compactness (nucA)          5.235523e-02
concavity (nucA)            7.929422e-02
concave points (nucA)       3.861717e-02
symmetry (nucA)             2.731942e-02
fractal dimension (nucA)    7.034862e-03
radius (nucB)               2.760385e-01
texture (nucB)              5.519793e-01
perimeter (nucB)            2.009288e+00
area (nucB)                 4.528241e+01
smoothness (nucB)           3.005043e-03
compactness (nucB)          1.789658e-02
concavity (nucB)            3.019872e-02
concave points (nucB)       6.173350e-03
symmetry (nucB)             8.264041e-03
fractal dimension (nucB)    2.646484e-03
radius (nucC)               4.822320e+00
texture (nucC)              6.141662e+00
perimeter (nucC)            3.347469e+01
area (nucC)                 5.678463e+02
smoothness (nucC)           2.281813e-02
compactness (nucC)          1.565232e-01
concavity (nucC)            2.079886e-01
concave points (nucC)       6.548425e-02
symmetry (nucC)             6.150821e-02
fractal dimension (nucC)    1.801738e-02
dtype: float64

#Filter/search/query on a dataframe

In [ ]:
#Get the value of a particular cell by position
row = 2
col = 10
df_cancer.iat[row, col]

0.2597

In [ ]:
#Get the value of a particular cell by column name and then, position
column_name = 'area (nucA)'
row = 2
df_cancer[column_name][2]

1203.0

In [ ]:
#Points to remember: Both the following syntax refer to the same dataframe
print(type(df_cancer))
print(type(df_cancer[[]]))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
#Points to remember: one pair of box-bracket ([]) denotes a series but two pairs of box-bracket ([[]]) denotes a data frame
column_name = 'id'
print(type(df_cancer[column_name]))
print(type(df_cancer[[column_name]]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
#Display some selected columns in a dataframe
column_name1 = 'smoothness (nucA)' #You may need to change it to just 'diagnosis' if you have changed it earlier
column_name2 = 'area (nucA)'
column_name3 = 'concave points (nucA)'
#df_cancer[column_name1, column_name2] #Invalid because df[] is a series, so canNOT have multiple columns
df_cancer[[column_name1, column_name2, column_name3]] #Valid because df[[]] is a dataframe, so can have multiple columns.

     smoothness (nucA)  area (nucA)  concave points (nucA)
1              0.08474       1326.0                0.07017
2              0.10960       1203.0                0.12790
3              0.14250        386.1                0.10520
4              0.10030       1297.0                0.10430
5              0.12780        477.1                0.08089
..                 ...          ...                    ...
564            0.11100       1479.0                0.13890
565            0.09780       1261.0                0.09791
566            0.08455        858.1                0.05302
567            0.11780       1265.0                0.15200
568            0.05263        181.0                0.00000

[568 rows x 3 columns]

In [ ]:
#Get the elements by boolean Search
column_name1 = 'diagnosis' #You may need to change it to just 'diagnosis' if you have changed it earlier
column_name2 = 'area (nucA)'
column_name3 = 'concave points (nucA)'
#df_cancer[ (df_cancer[column_name1] == 'M') ] #Show the records where diagnosis is M
#df_cancer[ (df_cancer[column_name1] == 'M') & (df_cancer[column_name3] < 0.074) ] #Show the records where diagnosis is M and concave points is less than 0.074
df_cancer[ (df_cancer[column_name1] == 'M') & (df_cancer[column_name3] < 0.074) ] [['id', 'diagnosis']] #Show only those three columns where the above condition is true

           id diagnosis
1      842517         M
7    84458202         M
10     845636         M
11   84610002         M
13     846381         M
..        ...       ...
489    913535         M
501     91504         M
514  91594602         M
536  91979701         M
566    926954         M

[73 rows x 2 columns]

#Filtering based on some statistics
Let us mix both filter/serach/query and maths/stats

In [ ]:
#DIY: Get the '%id' of those recods where area is less than the mean(area) but greater than the min(area)

display_column_name1 = 'id' #Change it to id if you have changed it earlier
analytic_column_name2 = 'area (nucA)'
df_cancer[ (df_cancer[analytic_column_name2] > df_cancer[analytic_column_name2].min()) & (df_cancer[analytic_column_name2] < df_cancer[analytic_column_name2].mean()) ] [[display_column_name1, analytic_column_name2]]

           id  area (nucA)
3    84348301        386.1
5      843786        477.1
7    84458202        577.9
8      844981        519.8
9    84501001        475.9
..        ...          ...
557    925236        271.3
559    925291        403.5
560    925292        600.4
561    925311        386.0
568     92751        181.0

[364 rows x 2 columns]

#Group By

In [37]:
#Read a file available over internet (Copy-paste the previous block so that I don't need to scroll too much)
#In this section, I will make some changes in my file and you should be able to see those changes in your program)
file_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSxuqWA__mPgb5p0abdX5MsV64mijIs_wblVo6j-H3vuSLgG8c_RirNMc1zHX_FCXdWgBgbv0VtCNgq/pub?output=csv'
df_cancer = pd.read_csv(file_url)
#type(df_cancer)
df_cancer

,%id,diagnosis (M=malignant; B=benign),radius (nucA),texture (nucA),perimeter (nucA),area (nucA),smoothness (nucA),compactness (nucA),concavity (nucA),concave points (nucA),...,radius (nucC),texture (nucC),perimeter (nucC),area (nucC),smoothness (nucC),compactness (nucC),concavity (nucC),concave points (nucC),symmetry (nucC),fractal dimension (nucC)
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [40]:
#You can group by based on as many columns as you want in comma separated fashion
#For one column you may not need to use the [] but that will not work for mutiple columns 
grouped_df_cancer = df_cancer.groupby(['diagnosis (M=malignant; B=benign)']) 
#for key, item in grouped_df_cancer: 
#    print(grouped_df_cancer.get_group(key)['%id'], "\n\n")
grouped_df_cancer

In [42]:
grouped_df_cancer = df_cancer.groupby(['diagnosis (M=malignant; B=benign)'])
grouped_df_cancer.head(4)

,%id,diagnosis (M=malignant; B=benign),radius (nucA),texture (nucA),perimeter (nucA),area (nucA),smoothness (nucA),compactness (nucA),concavity (nucA),concave points (nucA),...,radius (nucC),texture (nucC),perimeter (nucC),area (nucC),smoothness (nucC),compactness (nucC),concavity (nucC),concave points (nucC),symmetry (nucC),fractal dimension (nucC)
0,842302,M,17.990,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.71190,0.26540,0.4601,0.11890
1,842517,M,20.570,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.24160,0.18600,0.2750,0.08902
2,84300903,M,19.690,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.45040,0.24300,0.3613,0.08758
3,84348301,M,11.420,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.68690,0.25750,0.6638,0.17300
19,8510426,B,13.540,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,...,15.11,19.26,99.70,711.2,0.14400,0.17730,0.23900,0.12880,0.2977,0.07259
20,8510653,B,13.080,15.71,85.63,520.0,0.10750,0.12700,0.04568,0.03110,...,14.50,20.49,96.09,630.5,0.13120,0.27760,0.18900,0.07283,0.3184,0.08183
21,8510824,B,9.504,12.44,60.34,273.9,0.10240,0.06492,0.02956,0.02076,...,10.23,15.66,65.13,314.9,0.13240,0.11480,0.08867,0.06227,0.2450,0.07773
37,854941,B,13.030,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.02923,...,13.30,22.81,84.46,545.9,0.09701,0.04619,0.04833,0.05013,0.1987,0.06169

In [46]:
#See the grouped statistics for each column
grouped_df_cancer = df_cancer.groupby(['diagnosis (M=malignant; B=benign)']).agg('sum')
grouped_df_cancer

,%id,radius (nucA),texture (nucA),perimeter (nucA),area (nucA),smoothness (nucA),compactness (nucA),concavity (nucA),concave points (nucA),symmetry (nucA),...,radius (nucC),texture (nucC),perimeter (nucC),area (nucC),smoothness (nucC),compactness (nucC),concavity (nucC),concave points (nucC),symmetry (nucC),fractal dimension (nucC)
diagnosis (M=malignant; B=benign),,,,,,,,,,,,,,,,,,,,,
B,9476145391,4336.309,6395.57,27872.92,165216.1,33.01452,28.59021,16.442571,9.181114,62.1844,...,4776.589,8394.88,31061.12,199527.1,44.61054,65.21410,59.346867,26.576631,96.4778,28.36082
M,7805426694,3702.120,4580.24,24457.46,207415.8,21.81448,30.77981,34.084240,18.653880,40.8967,...,4480.580,6215.46,29970.51,301524.7,30.70719,79.46271,95.528380,38.634310,68.5752,19.40435